
server:
  port: 8083
spring:
  application:
    name: BILLING-SERVICE
  h2:
    console:
         enabled: true
  cloud:
    discovery:
      enabled: true
  datasource:
    url: jdbc:h2:mem:billing-db
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
